import type { Metadata } from 'next';
import '../../globals.css';
import { SidebarProvider } from '@/components/ui/sidebar';
import { Sidebar } from '@/components/appSidebar';
import { HeaderComponent } from '@/components/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <div className="flex h-screen w-screen">
        <Sidebar />
        <div className="flex flex-col flex-1">
          <HeaderComponent />
          <div className="flex-1 overflow-auto p-6  mx-auto w-full">
            <main className="w-full">{children}</main>
          </div>
        </div>
      </div>
    </SidebarProvider>
  );
}
